context:
  version: "1.42.11"

package:
  name: x-transformers
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/x/x-transformers/x_transformers-${{ version }}.tar.gz
  sha256: eb342ffc5b86193354f27dcdbfd3e13746dd102bf5ddffa21f3286fdc07bde0e

build:
  noarch: python 
  script: pip install . -v

requirements:
  # note that there is no build section
  host:
    - pip
    - python >=3.7
    - setuptools
    - wheel
  run:
    - python >=3.7
    - pytorch >= 2.0.0
    - einx >= 0.3.0
    - einops >= 0.8.0

tests:
  - python:
      imports:
        - x_transformers

about:
  homepage: https://github.com/lucidrains/x-transformers
  license: MIT
  license_file: LICENSE
  summary: A concise but complete full-attention transformer with a set of promising experimental features from various papers
  description: |
    A concise but fully-featured transformer, complete with a set of promising experimental features from various papers.
  documentation: https://github.com/lucidrains/x-transformers?tab=readme-ov-file#usage
